### ISSUE TITLE
Create Docs dir and empty files for later use

### ISSUE THREAD

**Issue by ErikSRoth** [RLTechsLLC/Server-Setup#5]
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] update gitignore for 'docs'
- [x] Create Docs Folder
- [x] Create CSS Folder
- [x] Create JS Folder
- [x] Create index Fie
- [ ] create Setup doc Fie
- [x] create scripts folder
```

**Comment by ErikSRoth** [comment]
Basic "Coming Soon" needs to be on the index page, then this will need to be pushed all the way out to release so it can be set up and linked to verify the docs will work with GitHub pages. See this page for more info... [https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
