### ISSUE TITLE
Create 'First' Contributer procedure and file

### ISSUE THREAD

**Issue by ErikSRoth** [RLTechsLLC/Server-Setup#7]
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] add contributers to main readme file
- [ ] add contributers.md file
- [ ] add githuub action for contributers
- [ ] make sure that the conributors file is only file modified with thistype of contribution.
```
